#This command is required at the top of every docker-compose/docker stack file the minimum version is 1 but recommended version is version 2 onwards for compose and 3 onwards for stack.
version: '3.1'

#This block named services includes all the information regarding the containers,volumes,ports,network,environment variables etc.
services:
    drupal:
#This command will download "drupal" official image with tag 8.2 from hub.docker.com.
        image: drupal:8.2
#This command will expose port 80 and publish it to port 8080.
        ports:
            - '8080:80'
#This command creates volumes for the drupal container
        volumes:
            - drupal_modules:/var/www/html/modules
            - drupal_profiles:/var/www/html/profiles
            - drupal_themes:/var/www/html/themes
            - drupal_sites:/var/www/html/sites
        
    postgres:
        image: postgres:12.1

#This command will store secrets inside the image at the path /run/secrets/ in a file with custom file name which will be put in place of <secrets_file_name>
        secrets:
            - <secrets_file_name>
            
#This will set the password for the postgres database within the image pulled above and the password will need to be extracted from the file /run/secrets/<custom_file_name>.       
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/<secrets_file_name>
            
#This will assign the datavolumes for drupal globally  
        volumes:
            - drupal-data:/var/lib/postgresql/data

#This command will globally declate the secret and its type, will create a secret with custom name as described above and will store it in /run/secrets within the service, external:true means that the secret will have to be stored in the file externally
secrets:
    <secrets_file_name>:
        external: true
volumes:
    drupal_modules:
    drupal_profiles:
    drupal_themes:
    drupal_sites:
    drupal-data: