



#This command will pull the nginx image with the tag "latest" from docker hub
FROM nginx:latest


#This command will move to the working directory /usr/share/nginx/html within the image
WORKDIR /usr/share/nginx/html

#This command will copy the index.html file present in the directory same as that of DockerFile and will paste it in the nginx image at the path /usr/share/nginx/html.
COPY index.html index.html
